-- ============================================================================
-- ICP Server Oracle Database Schema (Oracle Database 19c)
-- Run via SQL*Plus / SQLcl. PL/SQL blocks are terminated with a '/' line.
-- ============================================================================

-- Session-format safety net: make implicit string->timestamp conversions from
-- the application behave deterministically for every session in this schema.
BEGIN
  EXECUTE IMMEDIATE q'[CREATE OR REPLACE TRIGGER icp_set_nls_on_logon AFTER LOGON ON SCHEMA
  BEGIN
    EXECUTE IMMEDIATE 'ALTER SESSION SET NLS_TIMESTAMP_FORMAT = ''YYYY-MM-DD HH24:MI:SS.FF6''';
    EXECUTE IMMEDIATE 'ALTER SESSION SET NLS_DATE_FORMAT = ''YYYY-MM-DD HH24:MI:SS''';
  END;]';
END;
/

-- ============================================================================
-- ORGANIZATIONS
-- ============================================================================

CREATE TABLE organizations (
    org_id NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    org_name VARCHAR2(255 CHAR) NOT NULL UNIQUE,
    org_handle VARCHAR2(100 CHAR) NOT NULL UNIQUE,
    description CLOB NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- idx_org_handle omitted: the UNIQUE constraint on org_handle already creates
-- an index on the same column list (a duplicate raises ORA-01408).

CREATE OR REPLACE TRIGGER trg_organizations_updated_at
BEFORE UPDATE ON organizations
FOR EACH ROW
BEGIN
    :NEW.updated_at := CURRENT_TIMESTAMP;
END;
/

-- ============================================================================
-- USER MANAGEMENT & AUTHZ
-- ============================================================================

CREATE TABLE users (
    user_id CHAR(36) NOT NULL PRIMARY KEY,
    username VARCHAR2(255 CHAR) NOT NULL UNIQUE,
    display_name VARCHAR2(200 CHAR) NOT NULL,
    is_super_admin NUMBER(1) DEFAULT 0 NOT NULL CHECK (is_super_admin IN (0, 1)),
    is_project_author NUMBER(1) DEFAULT 0 NOT NULL CHECK (is_project_author IN (0, 1)),
    is_oidc_user NUMBER(1) DEFAULT 0 NOT NULL CHECK (is_oidc_user IN (0, 1)),
    require_password_change NUMBER(1) DEFAULT 0 NOT NULL CHECK (require_password_change IN (0, 1)),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- idx_username omitted: covered by the UNIQUE constraint on username (ORA-01408).
CREATE INDEX idx_super_admin ON users (is_super_admin);
CREATE INDEX idx_project_author ON users (is_project_author);

CREATE OR REPLACE TRIGGER trg_users_updated_at
BEFORE UPDATE ON users
FOR EACH ROW
BEGIN
    :NEW.updated_at := CURRENT_TIMESTAMP;
END;
/

-- ============================================================================
-- REFRESH TOKENS (for authentication session management)
-- ============================================================================

CREATE TABLE refresh_tokens (
    token_id CHAR(36) NOT NULL PRIMARY KEY,
    user_id CHAR(36) NOT NULL,
    token_hash VARCHAR2(255 CHAR) NOT NULL UNIQUE, -- SHA256 hash of token
    expires_at TIMESTAMP NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    last_used_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    revoked NUMBER(1) DEFAULT 0 NOT NULL CHECK (revoked IN (0, 1)),
    revoked_at TIMESTAMP NULL,
    user_agent VARCHAR2(500 CHAR) NULL,
    ip_address VARCHAR2(50 CHAR) NULL,
    CONSTRAINT fk_refresh_tokens_user FOREIGN KEY (user_id) REFERENCES users (user_id) ON DELETE CASCADE
);

CREATE INDEX idx_rt_user_id ON refresh_tokens (user_id);
-- idx_token_hash omitted: covered by the UNIQUE constraint on token_hash (ORA-01408).
CREATE INDEX idx_rt_expires_at ON refresh_tokens (expires_at);
CREATE INDEX idx_rt_revoked ON refresh_tokens (revoked);

-- MySQL maintains last_used_at via ON UPDATE CURRENT_TIMESTAMP (MSSQL uses a trigger).
CREATE OR REPLACE TRIGGER trg_refresh_tokens_last_used
BEFORE UPDATE ON refresh_tokens
FOR EACH ROW
BEGIN
    :NEW.last_used_at := CURRENT_TIMESTAMP;
END;
/

-- ============================================================================
-- PROJECTS / COMPONENTS / ENVIRONMENTS
-- ============================================================================

CREATE TABLE projects (
    project_id CHAR(36) PRIMARY KEY,
    org_id NUMBER(10) NOT NULL,
    name VARCHAR2(100 CHAR) NOT NULL,
    version VARCHAR2(50 CHAR) DEFAULT '1.0.0' NULL,
    created_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    handler VARCHAR2(200 CHAR) NOT NULL,
    region VARCHAR2(100 CHAR) NULL,
    description CLOB,
    default_deployment_pipeline_id CHAR(36) NULL,
    deployment_pipeline_ids CLOB NULL,
    type VARCHAR2(50 CHAR) NULL,
    git_provider VARCHAR2(50 CHAR) NULL,
    git_organization VARCHAR2(200 CHAR) NULL,
    repository VARCHAR2(200 CHAR) NULL,
    branch VARCHAR2(100 CHAR) NULL,
    secret_ref VARCHAR2(200 CHAR) NULL,
    owner_id CHAR(36) NULL, -- User ID of the project owner
    created_by VARCHAR2(200 CHAR) NULL, -- Display name of who created the project
    updated_by VARCHAR2(200 CHAR) NULL, -- Display name of who last updated the project
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_projects_owner FOREIGN KEY (owner_id) REFERENCES users (user_id) ON DELETE SET NULL,
    -- MySQL: ON DELETE RESTRICT. The Oracle default (NO ACTION) is equivalent (RESTRICT is not valid Oracle syntax).
    CONSTRAINT fk_projects_org FOREIGN KEY (org_id) REFERENCES organizations (org_id),
    CONSTRAINT uk_project_name_org UNIQUE (org_id, name), -- Allow same name in different orgs
    CONSTRAINT uk_project_handler_org UNIQUE (org_id, handler) -- Enforce unique handler per org
);

CREATE INDEX idx_proj_owner_id ON projects (owner_id);
CREATE INDEX idx_proj_org_id ON projects (org_id);

CREATE OR REPLACE TRIGGER trg_projects_updated_at
BEFORE UPDATE ON projects
FOR EACH ROW
BEGIN
    :NEW.updated_at := CURRENT_TIMESTAMP;
END;
/

-- Components belong to projects; users create components.
CREATE TABLE components (
    component_id CHAR(36) PRIMARY KEY,
    project_id CHAR(36) NOT NULL,
    name VARCHAR2(150 CHAR) NOT NULL,
    display_name VARCHAR2(200 CHAR) NOT NULL,
    description CLOB NULL,
    component_type VARCHAR2(10 CHAR) DEFAULT 'BI' NOT NULL CHECK (component_type IN ('MI', 'BI')),
    display_type VARCHAR2(50 CHAR) DEFAULT 'service' NOT NULL,
    component_sub_type VARCHAR2(50 CHAR) NULL,
    created_by CHAR(36) NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_by CHAR(36) NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_components_project FOREIGN KEY (project_id) REFERENCES projects (project_id) ON DELETE CASCADE,
    CONSTRAINT fk_components_created_by FOREIGN KEY (created_by) REFERENCES users (user_id) ON DELETE SET NULL,
    CONSTRAINT fk_components_updated_by FOREIGN KEY (updated_by) REFERENCES users (user_id) ON DELETE SET NULL,
    -- Prevent duplicate component names within the same project
    CONSTRAINT uk_component_project_name UNIQUE (project_id, name)
);

CREATE INDEX idx_comp_project_id ON components (project_id);

CREATE OR REPLACE TRIGGER trg_components_updated_at
BEFORE UPDATE ON components
FOR EACH ROW
BEGIN
    :NEW.updated_at := CURRENT_TIMESTAMP;
END;
/

-- Moesif metrics configuration for a component (kept separate from components to
-- isolate provider secrets and avoid sparse columns on the core table).
CREATE TABLE component_moesif_config (
    component_id CHAR(36) PRIMARY KEY,
    dashboards_created NUMBER(1) DEFAULT 0 NOT NULL CHECK (dashboards_created IN (0, 1)),
    workspace_id VARCHAR2(512 CHAR) NULL,
    management_key VARCHAR2(4000 CHAR) NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_moesif_config_component FOREIGN KEY (component_id) REFERENCES components (component_id) ON DELETE CASCADE
);

CREATE OR REPLACE TRIGGER trg_moesif_config_updated_at
BEFORE UPDATE ON component_moesif_config
FOR EACH ROW
BEGIN
    :NEW.updated_at := CURRENT_TIMESTAMP;
END;
/

CREATE TABLE environments (
    environment_id CHAR(36) PRIMARY KEY,
    name VARCHAR2(200 CHAR) NOT NULL UNIQUE, -- e.g., dev, stage, prod
    handler VARCHAR2(200 CHAR) NOT NULL UNIQUE,
    description CLOB NULL,
    region VARCHAR2(100 CHAR) NULL,
    cluster_id VARCHAR2(200 CHAR) NULL,
    choreo_env VARCHAR2(50 CHAR) NULL,
    external_apim_env_name VARCHAR2(200 CHAR) NULL,
    internal_apim_env_name VARCHAR2(200 CHAR) NULL,
    sandbox_apim_env_name VARCHAR2(200 CHAR) NULL,
    critical NUMBER(1) DEFAULT 0 NOT NULL CHECK (critical IN (0, 1)),
    dns_prefix VARCHAR2(100 CHAR) NULL,
    created_by CHAR(36) NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_by CHAR(36) NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_environments_created_by FOREIGN KEY (created_by) REFERENCES users (user_id) ON DELETE SET NULL,
    CONSTRAINT fk_environments_updated_by FOREIGN KEY (updated_by) REFERENCES users (user_id) ON DELETE SET NULL
);

CREATE OR REPLACE TRIGGER trg_environments_updated_at
BEFORE UPDATE ON environments
FOR EACH ROW
BEGIN
    :NEW.updated_at := CURRENT_TIMESTAMP;
END;
/

-- ============================================================================
-- ============================================================================
-- RBAC V2 - GROUP-BASED AUTHORIZATION
-- ============================================================================

-- User Groups table
CREATE TABLE user_groups (
    group_id VARCHAR2(36 CHAR) PRIMARY KEY,
    group_name VARCHAR2(255 CHAR) NOT NULL,
    org_uuid NUMBER(10) DEFAULT 1 NOT NULL,
    description CLOB,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_user_groups_org FOREIGN KEY (org_uuid) REFERENCES organizations (org_id) ON DELETE CASCADE,
    CONSTRAINT unique_group_name_org UNIQUE (group_name, org_uuid)
);

CREATE INDEX idx_ug_org_uuid ON user_groups (org_uuid);
CREATE INDEX idx_ug_group_name ON user_groups (group_name);

CREATE OR REPLACE TRIGGER trg_user_groups_updated_at
BEFORE UPDATE ON user_groups
FOR EACH ROW
BEGIN
    :NEW.updated_at := CURRENT_TIMESTAMP;
END;
/

-- Roles v2 table (new structure for permission-based RBAC)
CREATE TABLE roles_v2 (
    role_id VARCHAR2(36 CHAR) PRIMARY KEY,
    role_name VARCHAR2(255 CHAR) NOT NULL,
    org_id NUMBER(10) DEFAULT 1 NOT NULL,
    description CLOB,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_roles_v2_org FOREIGN KEY (org_id) REFERENCES organizations (org_id) ON DELETE CASCADE,
    CONSTRAINT unique_role_name_org UNIQUE (role_name, org_id)
);

CREATE INDEX idx_rv2_role_name ON roles_v2 (role_name);
CREATE INDEX idx_rv2_org_id ON roles_v2 (org_id);

CREATE OR REPLACE TRIGGER trg_roles_v2_updated_at
BEFORE UPDATE ON roles_v2
FOR EACH ROW
BEGIN
    :NEW.updated_at := CURRENT_TIMESTAMP;
END;
/

-- Permissions table with domain grouping
CREATE TABLE permissions (
    permission_id VARCHAR2(36 CHAR) PRIMARY KEY,
    permission_name VARCHAR2(255 CHAR) NOT NULL UNIQUE,
    permission_domain VARCHAR2(50 CHAR) NOT NULL CHECK (permission_domain IN (
        'Integration-Management',
        'Environment-Management',
        'Observability-Management',
        'Project-Management',
        'User-Management',
        'Workflow-Management'
    )),
    resource_type VARCHAR2(100 CHAR) NOT NULL,
    action VARCHAR2(100 CHAR) NOT NULL,
    description CLOB,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_perm_permission_domain ON permissions (permission_domain);
CREATE INDEX idx_perm_resource_type ON permissions (resource_type);
-- idx_permission_name omitted: covered by the UNIQUE constraint on permission_name (ORA-01408).

CREATE OR REPLACE TRIGGER trg_permissions_updated_at
BEFORE UPDATE ON permissions
FOR EACH ROW
BEGIN
    :NEW.updated_at := CURRENT_TIMESTAMP;
END;
/

-- Group-User mapping (Many-to-Many)
CREATE TABLE group_user_mapping (
    id NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    group_id VARCHAR2(36 CHAR) NOT NULL,
    -- CHAR(36) (MySQL: VARCHAR(36)) to match users.user_id. Oracle FKs require matching column types (ORA-02267).
    user_uuid CHAR(36) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_group_user_group FOREIGN KEY (group_id) REFERENCES user_groups (group_id) ON DELETE CASCADE,
    CONSTRAINT fk_group_user_user FOREIGN KEY (user_uuid) REFERENCES users (user_id) ON DELETE CASCADE,
    CONSTRAINT unique_group_user UNIQUE (group_id, user_uuid)
);

CREATE INDEX idx_gum_user_uuid ON group_user_mapping (user_uuid);
CREATE INDEX idx_gum_group_id ON group_user_mapping (group_id);

-- SSO group mappings (IdP claim value -> ICP group)
CREATE TABLE sso_group_mappings (
    mapping_id VARCHAR2(36 CHAR) PRIMARY KEY,
    org_uuid NUMBER(10) DEFAULT 1 NOT NULL,
    issuer VARCHAR2(255 CHAR) NOT NULL,
    claim_name VARCHAR2(128 CHAR) NOT NULL,
    claim_value VARCHAR2(255 CHAR) NOT NULL,
    group_id VARCHAR2(36 CHAR) NOT NULL,
    -- CHAR(36) to match projects.project_id / components.component_id (ORA-02267).
    project_uuid CHAR(36) NULL,
    integration_uuid CHAR(36) NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_sso_group_mapping_org FOREIGN KEY (org_uuid) REFERENCES organizations (org_id) ON DELETE CASCADE,
    CONSTRAINT fk_sso_group_mapping_group FOREIGN KEY (group_id) REFERENCES user_groups (group_id) ON DELETE CASCADE,
    CONSTRAINT fk_sso_group_mapping_project FOREIGN KEY (project_uuid) REFERENCES projects (project_id) ON DELETE CASCADE,
    CONSTRAINT fk_sso_group_mapping_integration FOREIGN KEY (integration_uuid) REFERENCES components (component_id) ON DELETE CASCADE,
    -- Integration-scoped mappings require a project for navigation
    CONSTRAINT chk_sso_mapping_integration_requires_project
        CHECK (integration_uuid IS NULL OR project_uuid IS NOT NULL),
    CONSTRAINT unique_sso_group_mapping UNIQUE (org_uuid, issuer, claim_name, claim_value, group_id)
);

CREATE INDEX idx_sgm_org_uuid ON sso_group_mappings (org_uuid);
CREATE INDEX idx_sgm_issuer_claim ON sso_group_mappings (issuer, claim_name, claim_value);
CREATE INDEX idx_sgm_group_id ON sso_group_mappings (group_id);
CREATE INDEX idx_sgm_project_uuid ON sso_group_mappings (project_uuid);
CREATE INDEX idx_sgm_integration_uuid ON sso_group_mappings (integration_uuid);

CREATE OR REPLACE TRIGGER trg_sso_group_mappings_updated_at
BEFORE UPDATE ON sso_group_mappings
FOR EACH ROW
BEGIN
    :NEW.updated_at := CURRENT_TIMESTAMP;
END;
/

-- Federated group-user mappings (SSO-owned memberships)
CREATE TABLE federated_group_user_mapping (
    id NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    org_uuid NUMBER(10) DEFAULT 1 NOT NULL,
    issuer VARCHAR2(255 CHAR) NOT NULL,
    -- CHAR(36) to match users.user_id, and to keep the UNION in
    -- v_effective_group_user_mapping type-compatible with group_user_mapping.
    user_uuid CHAR(36) NOT NULL,
    group_id VARCHAR2(36 CHAR) NOT NULL,
    claim_name VARCHAR2(128 CHAR) NOT NULL,
    claim_value VARCHAR2(255 CHAR) NOT NULL,
    last_seen_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_fed_group_user_org FOREIGN KEY (org_uuid) REFERENCES organizations (org_id) ON DELETE CASCADE,
    CONSTRAINT fk_fed_group_user_user FOREIGN KEY (user_uuid) REFERENCES users (user_id) ON DELETE CASCADE,
    CONSTRAINT fk_fed_group_user_group FOREIGN KEY (group_id) REFERENCES user_groups (group_id) ON DELETE CASCADE,
    CONSTRAINT unique_fed_group_user_claim UNIQUE (org_uuid, issuer, user_uuid, group_id, claim_name, claim_value)
);

CREATE INDEX idx_fgum_user_uuid ON federated_group_user_mapping (user_uuid);
CREATE INDEX idx_fgum_group_id ON federated_group_user_mapping (group_id);
CREATE INDEX idx_fgum_issuer_claim ON federated_group_user_mapping (issuer, claim_name, claim_value);

CREATE OR REPLACE TRIGGER trg_fed_group_user_updated_at
BEFORE UPDATE ON federated_group_user_mapping
FOR EACH ROW
BEGIN
    :NEW.updated_at := CURRENT_TIMESTAMP;
END;
/

-- Group-Role mapping with context (Many-to-Many with hierarchical scoping)
CREATE TABLE group_role_mapping (
    id NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    group_id VARCHAR2(36 CHAR) NOT NULL,
    role_id VARCHAR2(36 CHAR) NOT NULL,
    org_uuid NUMBER(10) NULL,
    project_uuid CHAR(36) NULL,
    env_uuid CHAR(36) NULL,
    integration_uuid CHAR(36) NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_grp_role_group FOREIGN KEY (group_id) REFERENCES user_groups (group_id) ON DELETE CASCADE,
    CONSTRAINT fk_grp_role_role FOREIGN KEY (role_id) REFERENCES roles_v2 (role_id) ON DELETE CASCADE,
    CONSTRAINT fk_grp_role_org FOREIGN KEY (org_uuid) REFERENCES organizations (org_id) ON DELETE CASCADE,
    CONSTRAINT fk_grp_role_project FOREIGN KEY (project_uuid) REFERENCES projects (project_id) ON DELETE CASCADE,
    CONSTRAINT fk_grp_role_env FOREIGN KEY (env_uuid) REFERENCES environments (environment_id) ON DELETE CASCADE,
    CONSTRAINT fk_grp_role_integration FOREIGN KEY (integration_uuid) REFERENCES components (component_id) ON DELETE CASCADE,
    -- Integration access requires project for navigation
    CONSTRAINT chk_integration_requires_project
        CHECK (integration_uuid IS NULL OR project_uuid IS NOT NULL),
    -- NOTE: Oracle unique constraints compare rows with partially-NULL keys
    -- (MySQL treats any NULL key column as distinct). See translation notes.
    CONSTRAINT unique_group_role_context UNIQUE (group_id, role_id, org_uuid, project_uuid, env_uuid, integration_uuid)
);

CREATE INDEX idx_grm_group_id ON group_role_mapping (group_id);
CREATE INDEX idx_grm_role_id ON group_role_mapping (role_id);
CREATE INDEX idx_grm_org_uuid ON group_role_mapping (org_uuid);
CREATE INDEX idx_grm_project_uuid ON group_role_mapping (project_uuid);
CREATE INDEX idx_grm_env_uuid ON group_role_mapping (env_uuid);
CREATE INDEX idx_grm_integration_uuid ON group_role_mapping (integration_uuid);
CREATE INDEX idx_grm_group_project ON group_role_mapping (group_id, project_uuid);
CREATE INDEX idx_grm_group_env ON group_role_mapping (group_id, env_uuid);

-- Role-Permission mapping (Many-to-Many)
CREATE TABLE role_permission_mapping (
    id NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    role_id VARCHAR2(36 CHAR) NOT NULL,
    permission_id VARCHAR2(36 CHAR) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_role_perm_role FOREIGN KEY (role_id) REFERENCES roles_v2 (role_id) ON DELETE CASCADE,
    CONSTRAINT fk_role_perm_permission FOREIGN KEY (permission_id) REFERENCES permissions (permission_id) ON DELETE CASCADE,
    CONSTRAINT unique_role_permission UNIQUE (role_id, permission_id)
);

CREATE INDEX idx_rpm_role_id ON role_permission_mapping (role_id);
CREATE INDEX idx_rpm_permission_id ON role_permission_mapping (permission_id);

-- ============================================================================
-- RBAC V2 VIEWS
-- ============================================================================

-- View: Effective user group memberships from manual and SSO-owned sources
CREATE OR REPLACE VIEW v_effective_group_user_mapping AS
SELECT user_uuid, group_id
FROM group_user_mapping
UNION
SELECT user_uuid, group_id
FROM federated_group_user_mapping;

-- View: User's accessible projects
CREATE OR REPLACE VIEW v_user_project_access AS
-- Direct project-level access
SELECT DISTINCT
    gum.user_uuid,
    grm.project_uuid,
    p.name AS project_name,
    p.org_id AS org_uuid,
    grm.role_id,
    'project' AS access_level
FROM v_effective_group_user_mapping gum
INNER JOIN group_role_mapping grm ON gum.group_id = grm.group_id
INNER JOIN projects p ON grm.project_uuid = p.project_id
WHERE grm.project_uuid IS NOT NULL AND grm.integration_uuid IS NULL
UNION
-- Org-level access (inherits all projects)
SELECT DISTINCT
    gum.user_uuid,
    p.project_id AS project_uuid,
    p.name AS project_name,
    p.org_id AS org_uuid,
    grm.role_id,
    'org' AS access_level
FROM v_effective_group_user_mapping gum
INNER JOIN group_role_mapping grm ON gum.group_id = grm.group_id
INNER JOIN projects p ON grm.org_uuid = p.org_id
WHERE grm.org_uuid IS NOT NULL
  AND grm.project_uuid IS NULL
  AND grm.integration_uuid IS NULL
UNION
-- Integration-level access (project must be visible for navigation)
SELECT DISTINCT
    gum.user_uuid,
    grm.project_uuid,
    p.name AS project_name,
    p.org_id AS org_uuid,
    grm.role_id,
    'integration' AS access_level
FROM v_effective_group_user_mapping gum
INNER JOIN group_role_mapping grm ON gum.group_id = grm.group_id
INNER JOIN projects p ON grm.project_uuid = p.project_id
WHERE grm.integration_uuid IS NOT NULL;

-- View: User's accessible integrations
CREATE OR REPLACE VIEW v_user_integration_access AS
-- Direct integration-level access
SELECT DISTINCT
    gum.user_uuid,
    grm.integration_uuid,
    c.name AS integration_name,
    c.project_id AS project_uuid,
    grm.env_uuid,
    grm.role_id,
    'integration' AS access_level
FROM v_effective_group_user_mapping gum
INNER JOIN group_role_mapping grm ON gum.group_id = grm.group_id
INNER JOIN components c ON grm.integration_uuid = c.component_id
WHERE grm.integration_uuid IS NOT NULL
UNION
-- Project-level access (inherits all integrations in project)
SELECT DISTINCT
    gum.user_uuid,
    c.component_id AS integration_uuid,
    c.name AS integration_name,
    c.project_id AS project_uuid,
    grm.env_uuid,
    grm.role_id,
    'project' AS access_level
FROM v_effective_group_user_mapping gum
INNER JOIN group_role_mapping grm ON gum.group_id = grm.group_id
INNER JOIN components c ON grm.project_uuid = c.project_id
WHERE grm.project_uuid IS NOT NULL
  AND grm.integration_uuid IS NULL
UNION
-- Org-level access (inherits all integrations in all projects)
SELECT DISTINCT
    gum.user_uuid,
    c.component_id AS integration_uuid,
    c.name AS integration_name,
    c.project_id AS project_uuid,
    grm.env_uuid,
    grm.role_id,
    'org' AS access_level
FROM v_effective_group_user_mapping gum
INNER JOIN group_role_mapping grm ON gum.group_id = grm.group_id
INNER JOIN projects p ON grm.org_uuid = p.org_id
INNER JOIN components c ON p.project_id = c.project_id
WHERE grm.org_uuid IS NOT NULL
  AND grm.project_uuid IS NULL
  AND grm.integration_uuid IS NULL;

-- View: User's environment access/restrictions
CREATE OR REPLACE VIEW v_user_environment_access AS
SELECT DISTINCT
    gum.user_uuid,
    grm.env_uuid,
    grm.project_uuid,
    grm.integration_uuid,
    grm.role_id,
    CASE
        WHEN grm.integration_uuid IS NOT NULL THEN 'integration'
        WHEN grm.project_uuid IS NOT NULL THEN 'project'
        ELSE 'org'
    END AS scope_level
FROM v_effective_group_user_mapping gum
INNER JOIN group_role_mapping grm ON gum.group_id = grm.group_id
WHERE grm.env_uuid IS NOT NULL OR grm.org_uuid IS NOT NULL;

-- ============================================================================
-- RBAC V2 SEED DATA
-- ============================================================================

-- Insert default organization (required for foreign key constraints)
INSERT INTO
    organizations (org_id, org_name, org_handle)
VALUES (
        1,
        'Default Organization',
        'default'
    );

-- Re-seed the identity sequence past the explicitly inserted org_id values
-- so later identity-generated values do not collide.
ALTER TABLE organizations MODIFY (org_id GENERATED BY DEFAULT ON NULL AS IDENTITY (START WITH LIMIT VALUE));

-- Insert pre-defined roles
-- (MySQL UUID() -> dashed lowercase UUID derived from SYS_GUID())
INSERT INTO roles_v2 (role_id, role_name, org_id, description) VALUES
(REGEXP_REPLACE(LOWER(RAWTOHEX(SYS_GUID())), '^(.{8})(.{4})(.{4})(.{4})(.{12})$', '\1-\2-\3-\4-\5'), 'Super Admin', 1, 'Full access to all resources and permissions');
INSERT INTO roles_v2 (role_id, role_name, org_id, description) VALUES
(REGEXP_REPLACE(LOWER(RAWTOHEX(SYS_GUID())), '^(.{8})(.{4})(.{4})(.{4})(.{12})$', '\1-\2-\3-\4-\5'), 'Admin', 1, 'Administrative access to projects and integrations');
INSERT INTO roles_v2 (role_id, role_name, org_id, description) VALUES
(REGEXP_REPLACE(LOWER(RAWTOHEX(SYS_GUID())), '^(.{8})(.{4})(.{4})(.{4})(.{12})$', '\1-\2-\3-\4-\5'), 'Developer', 1, 'Development access with limited permissions');
INSERT INTO roles_v2 (role_id, role_name, org_id, description) VALUES
(REGEXP_REPLACE(LOWER(RAWTOHEX(SYS_GUID())), '^(.{8})(.{4})(.{4})(.{4})(.{12})$', '\1-\2-\3-\4-\5'), 'Project Admin', 1, 'Administrative access to a specific project');
INSERT INTO roles_v2 (role_id, role_name, org_id, description) VALUES
(REGEXP_REPLACE(LOWER(RAWTOHEX(SYS_GUID())), '^(.{8})(.{4})(.{4})(.{4})(.{12})$', '\1-\2-\3-\4-\5'), 'Viewer', 1, 'Read-only access with view permissions only');

-- Insert permissions for all domains
-- Integration Management
INSERT INTO permissions (permission_id, permission_name, permission_domain, resource_type, action, description) VALUES
(REGEXP_REPLACE(LOWER(RAWTOHEX(SYS_GUID())), '^(.{8})(.{4})(.{4})(.{4})(.{12})$', '\1-\2-\3-\4-\5'), 'integration_mgt:view', 'Integration-Management', 'integration', 'view', 'View integrations');
INSERT INTO permissions (permission_id, permission_name, permission_domain, resource_type, action, description) VALUES
(REGEXP_REPLACE(LOWER(RAWTOHEX(SYS_GUID())), '^(.{8})(.{4})(.{4})(.{4})(.{12})$', '\1-\2-\3-\4-\5'), 'integration_mgt:edit', 'Integration-Management', 'integration', 'edit', 'Edit integrations');
INSERT INTO permissions (permission_id, permission_name, permission_domain, resource_type, action, description) VALUES
(REGEXP_REPLACE(LOWER(RAWTOHEX(SYS_GUID())), '^(.{8})(.{4})(.{4})(.{4})(.{12})$', '\1-\2-\3-\4-\5'), 'integration_mgt:manage', 'Integration-Management', 'integration', 'manage', 'Create, edit, and delete integrations');

-- Environment Management
INSERT INTO permissions (permission_id, permission_name, permission_domain, resource_type, action, description) VALUES
(REGEXP_REPLACE(LOWER(RAWTOHEX(SYS_GUID())), '^(.{8})(.{4})(.{4})(.{4})(.{12})$', '\1-\2-\3-\4-\5'), 'environment_mgt:manage', 'Environment-Management', 'environment', 'manage', 'Create and delete environments');
INSERT INTO permissions (permission_id, permission_name, permission_domain, resource_type, action, description) VALUES
(REGEXP_REPLACE(LOWER(RAWTOHEX(SYS_GUID())), '^(.{8})(.{4})(.{4})(.{4})(.{12})$', '\1-\2-\3-\4-\5'), 'environment_mgt:manage_nonprod', 'Environment-Management', 'environment', 'manage', 'Create and delete non-production environments');

-- Project Management
INSERT INTO permissions (permission_id, permission_name, permission_domain, resource_type, action, description) VALUES
(REGEXP_REPLACE(LOWER(RAWTOHEX(SYS_GUID())), '^(.{8})(.{4})(.{4})(.{4})(.{12})$', '\1-\2-\3-\4-\5'), 'project_mgt:view', 'Project-Management', 'project', 'view', 'View projects');
INSERT INTO permissions (permission_id, permission_name, permission_domain, resource_type, action, description) VALUES
(REGEXP_REPLACE(LOWER(RAWTOHEX(SYS_GUID())), '^(.{8})(.{4})(.{4})(.{4})(.{12})$', '\1-\2-\3-\4-\5'), 'project_mgt:edit', 'Project-Management', 'project', 'edit', 'Edit projects');
INSERT INTO permissions (permission_id, permission_name, permission_domain, resource_type, action, description) VALUES
(REGEXP_REPLACE(LOWER(RAWTOHEX(SYS_GUID())), '^(.{8})(.{4})(.{4})(.{4})(.{12})$', '\1-\2-\3-\4-\5'), 'project_mgt:manage', 'Project-Management', 'project', 'manage', 'Create, edit, and delete projects');

-- Observability Management
INSERT INTO permissions (permission_id, permission_name, permission_domain, resource_type, action, description) VALUES
(REGEXP_REPLACE(LOWER(RAWTOHEX(SYS_GUID())), '^(.{8})(.{4})(.{4})(.{4})(.{12})$', '\1-\2-\3-\4-\5'), 'observability_mgt:view_logs', 'Observability-Management', 'logs', 'view', 'View logs');
INSERT INTO permissions (permission_id, permission_name, permission_domain, resource_type, action, description) VALUES
(REGEXP_REPLACE(LOWER(RAWTOHEX(SYS_GUID())), '^(.{8})(.{4})(.{4})(.{4})(.{12})$', '\1-\2-\3-\4-\5'), 'observability_mgt:view_insights', 'Observability-Management', 'insights', 'view', 'View insights');

-- User Management
INSERT INTO permissions (permission_id, permission_name, permission_domain, resource_type, action, description) VALUES
(REGEXP_REPLACE(LOWER(RAWTOHEX(SYS_GUID())), '^(.{8})(.{4})(.{4})(.{4})(.{12})$', '\1-\2-\3-\4-\5'), 'user_mgt:manage_users', 'User-Management', 'user', 'manage', 'Create, update, and delete users');
INSERT INTO permissions (permission_id, permission_name, permission_domain, resource_type, action, description) VALUES
(REGEXP_REPLACE(LOWER(RAWTOHEX(SYS_GUID())), '^(.{8})(.{4})(.{4})(.{4})(.{12})$', '\1-\2-\3-\4-\5'), 'user_mgt:update_users', 'User-Management', 'user', 'update', 'Assign user groups');
INSERT INTO permissions (permission_id, permission_name, permission_domain, resource_type, action, description) VALUES
(REGEXP_REPLACE(LOWER(RAWTOHEX(SYS_GUID())), '^(.{8})(.{4})(.{4})(.{4})(.{12})$', '\1-\2-\3-\4-\5'), 'user_mgt:manage_groups', 'User-Management', 'group', 'manage', 'Create, update, and delete groups');
INSERT INTO permissions (permission_id, permission_name, permission_domain, resource_type, action, description) VALUES
(REGEXP_REPLACE(LOWER(RAWTOHEX(SYS_GUID())), '^(.{8})(.{4})(.{4})(.{4})(.{12})$', '\1-\2-\3-\4-\5'), 'user_mgt:manage_roles', 'User-Management', 'role', 'manage', 'Create, update, and delete roles');
INSERT INTO permissions (permission_id, permission_name, permission_domain, resource_type, action, description) VALUES
(REGEXP_REPLACE(LOWER(RAWTOHEX(SYS_GUID())), '^(.{8})(.{4})(.{4})(.{4})(.{12})$', '\1-\2-\3-\4-\5'), 'user_mgt:update_group_roles', 'User-Management', 'group-role', 'update', 'Map roles to groups');

-- Workflow Management permissions
INSERT INTO permissions (permission_id, permission_name, permission_domain, resource_type, action, description) VALUES
('a1f4c2e0-0000-4000-8000-000000000001', 'workflow_mgt:view_human_tasks', 'Workflow-Management', 'human_task', 'view', 'View human tasks');
INSERT INTO permissions (permission_id, permission_name, permission_domain, resource_type, action, description) VALUES
('a1f4c2e0-0000-4000-8000-000000000002', 'workflow_mgt:manage_human_tasks', 'Workflow-Management', 'human_task', 'manage', 'Complete, fail and cancel human tasks');
INSERT INTO permissions (permission_id, permission_name, permission_domain, resource_type, action, description) VALUES
('a1f4c2e0-0000-4000-8000-000000000003', 'workflow_mgt:view_workflows', 'Workflow-Management', 'workflow', 'view', 'View workflow executions');
INSERT INTO permissions (permission_id, permission_name, permission_domain, resource_type, action, description) VALUES
('a1f4c2e0-0000-4000-8000-000000000004', 'workflow_mgt:manage_workflows', 'Workflow-Management', 'workflow', 'manage', 'Start, suspend, resume, cancel and terminate workflow executions');

-- Map Super Admin to ALL permissions
INSERT INTO role_permission_mapping (role_id, permission_id)
SELECT
    (SELECT role_id FROM roles_v2 WHERE role_name = 'Super Admin'),
    permission_id
FROM permissions;

-- Map Admin to all permissions except User Management
INSERT INTO role_permission_mapping (role_id, permission_id)
SELECT
    (SELECT role_id FROM roles_v2 WHERE role_name = 'Admin'),
    permission_id
FROM permissions
WHERE permission_domain != 'User-Management';

-- Map Developer to specific permissions
INSERT INTO role_permission_mapping (role_id, permission_id)
SELECT
    (SELECT role_id FROM roles_v2 WHERE role_name = 'Developer'),
    permission_id
FROM permissions
WHERE permission_name IN (
    'integration_mgt:view',
    'integration_mgt:edit',
    'environment_mgt:manage_nonprod',
    'project_mgt:view',
    'project_mgt:edit',
    'observability_mgt:view_logs',
    'observability_mgt:view_insights'
);

-- Map Project Admin to project-specific admin permissions
INSERT INTO role_permission_mapping (role_id, permission_id)
SELECT
    (SELECT role_id FROM roles_v2 WHERE role_name = 'Project Admin'),
    permission_id
FROM permissions
WHERE permission_name IN (
    'project_mgt:manage',
    'integration_mgt:manage',
    'user_mgt:update_group_roles'
);

-- Map Viewer to view-only permissions
INSERT INTO role_permission_mapping (role_id, permission_id)
SELECT
    (SELECT role_id FROM roles_v2 WHERE role_name = 'Viewer'),
    permission_id
FROM permissions
WHERE permission_name IN (
    'integration_mgt:view',
    'project_mgt:view',
    'observability_mgt:view_logs',
    'observability_mgt:view_insights'
);

-- Map Workflow human-task permissions to operational roles (Super Admin/Admin covered above)
INSERT INTO role_permission_mapping (role_id, permission_id)
SELECT r.role_id, p.permission_id
FROM roles_v2 r, permissions p
WHERE p.permission_name IN ('workflow_mgt:view_human_tasks', 'workflow_mgt:manage_human_tasks')
    AND (r.role_name IN ('Developer', 'Project Admin') OR (r.role_name = 'Viewer' AND p.permission_name = 'workflow_mgt:view_human_tasks'));

-- Map Workflow execution permissions to admin roles (Super Admin/Admin covered above)
INSERT INTO role_permission_mapping (role_id, permission_id)
SELECT r.role_id, p.permission_id
FROM roles_v2 r, permissions p
WHERE (p.permission_name = 'workflow_mgt:view_workflows' AND r.role_name IN ('Developer', 'Project Admin'))
    OR (p.permission_name = 'workflow_mgt:manage_workflows' AND r.role_name = 'Project Admin');

-- Create default groups
INSERT INTO user_groups (group_id, group_name, org_uuid, description) VALUES
(REGEXP_REPLACE(LOWER(RAWTOHEX(SYS_GUID())), '^(.{8})(.{4})(.{4})(.{4})(.{12})$', '\1-\2-\3-\4-\5'), 'Super Admins', 1, 'Group for super administrators with full access');
INSERT INTO user_groups (group_id, group_name, org_uuid, description) VALUES
(REGEXP_REPLACE(LOWER(RAWTOHEX(SYS_GUID())), '^(.{8})(.{4})(.{4})(.{4})(.{12})$', '\1-\2-\3-\4-\5'), 'Administrators', 1, 'Group for administrators');
INSERT INTO user_groups (group_id, group_name, org_uuid, description) VALUES
(REGEXP_REPLACE(LOWER(RAWTOHEX(SYS_GUID())), '^(.{8})(.{4})(.{4})(.{4})(.{12})$', '\1-\2-\3-\4-\5'), 'Developers', 1, 'Group for developers');

-- Map Super Admins group to Super Admin role at org level
INSERT INTO group_role_mapping (group_id, role_id, org_uuid)
SELECT
    (SELECT group_id FROM user_groups WHERE group_name = 'Super Admins'),
    (SELECT role_id FROM roles_v2 WHERE role_name = 'Super Admin'),
    1
FROM dual;

COMMIT;

-- ============================================================================
-- RUNTIMES & ARTIFACTS
-- ============================================================================

CREATE TABLE runtimes (
    runtime_id CHAR(36) NOT NULL PRIMARY KEY,
    name VARCHAR2(100 CHAR) NULL,
    project_id CHAR(36) NOT NULL,
    component_id CHAR(36) NOT NULL,
    environment_id CHAR(36) NOT NULL,
    runtime_type VARCHAR2(10 CHAR) NOT NULL CHECK (runtime_type IN ('MI', 'BI')),
    status VARCHAR2(20 CHAR) DEFAULT 'OFFLINE' NOT NULL CHECK (status IN (
        'RUNNING',
        'FAILED',
        'DISABLED',
        'OFFLINE'
    )),
    version VARCHAR2(50 CHAR) NULL,
    runtime_hostname VARCHAR2(255 CHAR) NULL,
    runtime_port VARCHAR2(10 CHAR) NULL,
    callback_url VARCHAR2(500 CHAR) NULL,
    wf_boosted_until NUMBER(19),
    try_it_host VARCHAR2(255 CHAR) NULL,
    platform_name VARCHAR2(50 CHAR) DEFAULT 'ballerina' NOT NULL,
    platform_version VARCHAR2(50 CHAR) NULL,
    platform_home VARCHAR2(255 CHAR) NULL,
    os_name VARCHAR2(50 CHAR) NULL,
    os_version VARCHAR2(50 CHAR) NULL,
    carbon_home VARCHAR2(500 CHAR) NULL,
    java_vendor VARCHAR2(100 CHAR) NULL,
    java_version VARCHAR2(50 CHAR) NULL,
    total_memory NUMBER(19) NULL,
    free_memory NUMBER(19) NULL,
    max_memory NUMBER(19) NULL,
    used_memory NUMBER(19) NULL,
    os_arch VARCHAR2(50 CHAR) NULL,
    server_name VARCHAR2(200 CHAR) NULL,
    registration_time TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP(6) NOT NULL,
    last_heartbeat TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP(6) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_runtime_project FOREIGN KEY (project_id) REFERENCES projects (project_id) ON DELETE CASCADE,
    CONSTRAINT fk_runtime_component FOREIGN KEY (component_id) REFERENCES components (component_id) ON DELETE CASCADE,
    CONSTRAINT fk_runtime_env FOREIGN KEY (environment_id) REFERENCES environments (environment_id) ON DELETE CASCADE,
    CONSTRAINT uq_runtime_identity UNIQUE (component_id, environment_id, name)
);

CREATE INDEX idx_rt_runtime_type ON runtimes (runtime_type);
CREATE INDEX idx_rt_status ON runtimes (status);
CREATE INDEX idx_rt_env ON runtimes (environment_id);
CREATE INDEX idx_rt_component ON runtimes (component_id);
CREATE INDEX idx_rt_project ON runtimes (project_id);
CREATE INDEX idx_rt_last_heartbeat ON runtimes (last_heartbeat);

CREATE OR REPLACE TRIGGER trg_runtimes_updated_at
BEFORE UPDATE ON runtimes
FOR EACH ROW
BEGIN
    :NEW.updated_at := CURRENT_TIMESTAMP;
END;
/

-- Org-level secrets with key_id for JWT HMAC authentication.
-- Lazily bound to a project+component on first heartbeat (M2).
CREATE TABLE org_secrets (
    key_id         VARCHAR2(16 CHAR)  NOT NULL,
    environment_id CHAR(36)           NOT NULL,
    key_material   VARCHAR2(256 CHAR) NOT NULL,
    project_id     CHAR(36)           NULL,
    component_id   CHAR(36)           NULL,
    project_handler VARCHAR2(255 CHAR) NULL,
    component_name  VARCHAR2(255 CHAR) NULL,
    runtime_type    VARCHAR2(8 CHAR)   NULL,
    bound_at       TIMESTAMP          NULL,
    created_at     TIMESTAMP          DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_by     CHAR(36)           NULL,
    PRIMARY KEY (key_id),
    CONSTRAINT fk_org_secrets_project     FOREIGN KEY (project_id)     REFERENCES projects (project_id)          ON DELETE CASCADE,
    CONSTRAINT fk_org_secrets_component   FOREIGN KEY (component_id)   REFERENCES components (component_id)      ON DELETE CASCADE,
    CONSTRAINT fk_org_secrets_environment FOREIGN KEY (environment_id) REFERENCES environments (environment_id)   ON DELETE CASCADE,
    CONSTRAINT fk_org_secrets_created_by  FOREIGN KEY (created_by)     REFERENCES users (user_id)                ON DELETE SET NULL
);

CREATE INDEX idx_org_secrets_environment ON org_secrets (environment_id);

ALTER TABLE runtimes ADD key_id VARCHAR2(16 CHAR) NULL;
ALTER TABLE runtimes ADD CONSTRAINT fk_runtime_key_id FOREIGN KEY (key_id) REFERENCES org_secrets (key_id) ON DELETE SET NULL;

-- Services deployed on a runtime
CREATE TABLE bi_service_artifacts (
    runtime_id CHAR(36) NOT NULL,
    service_name VARCHAR2(100 CHAR) NOT NULL,
    service_package VARCHAR2(200 CHAR) NOT NULL,
    base_path VARCHAR2(500 CHAR) NULL,
    state VARCHAR2(20 CHAR) DEFAULT 'enabled' NOT NULL CHECK (state IN (
        'enabled',
        'disabled'
    )),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    PRIMARY KEY (runtime_id, service_name, service_package),
    CONSTRAINT fk_bi_service_artifacts_runtime FOREIGN KEY (runtime_id) REFERENCES runtimes (runtime_id) ON DELETE CASCADE
);

CREATE INDEX idx_rs_runtime_id ON bi_service_artifacts (runtime_id);
CREATE INDEX idx_rs_service_name ON bi_service_artifacts (service_name);
CREATE INDEX idx_rs_service_package ON bi_service_artifacts (service_package);
CREATE INDEX idx_rs_state ON bi_service_artifacts (state);

CREATE OR REPLACE TRIGGER trg_bi_service_artifacts_updated_at
BEFORE UPDATE ON bi_service_artifacts
FOR EACH ROW
BEGIN
    :NEW.updated_at := CURRENT_TIMESTAMP;
END;
/

-- Resources inside a service (HTTP resources etc.)
CREATE TABLE bi_service_resource_artifacts (
  -- CHAR(36) (MySQL: VARCHAR(100)) to match runtimes.runtime_id. Oracle FKs require matching column types (ORA-02267).
  runtime_id    CHAR(36) NOT NULL,
  service_name  VARCHAR2(100 CHAR) NOT NULL,
  resource_url  VARCHAR2(1000 CHAR) NOT NULL,
  methods       CLOB NOT NULL,  -- Array of HTTP methods (JSON)
  -- Generated (virtual) column for indexing first method (example pattern)
  method_first  VARCHAR2(20)
    GENERATED ALWAYS AS (JSON_VALUE(methods, '$[0]' RETURNING VARCHAR2(20))) VIRTUAL,
  created_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  PRIMARY KEY (runtime_id, service_name, resource_url),
  CONSTRAINT fk_bi_service_resource_artifacts_runtime FOREIGN KEY (runtime_id) REFERENCES runtimes (runtime_id) ON DELETE CASCADE
);

CREATE INDEX idx_sr_runtime_service ON bi_service_resource_artifacts (runtime_id, service_name);
CREATE INDEX idx_sr_resource_url ON bi_service_resource_artifacts (resource_url);
CREATE INDEX idx_sr_method_first ON bi_service_resource_artifacts (method_first);

CREATE OR REPLACE TRIGGER trg_bi_service_resource_updated
BEFORE UPDATE ON bi_service_resource_artifacts
FOR EACH ROW
BEGIN
    :NEW.updated_at := CURRENT_TIMESTAMP;
END;
/

-- OpenAPI (Swagger) definitions packed into a BI runtime's JAR by the swagger-pack compiler
-- plugin, reported via the full heartbeat's optional openApiDefinitions field.
CREATE TABLE bi_service_openapi_definitions (
  runtime_id  CHAR(36) NOT NULL,
  file_name   VARCHAR2(300 CHAR) NOT NULL,
  definition  CLOB NOT NULL,
  created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  PRIMARY KEY (runtime_id, file_name),
  CONSTRAINT fk_bi_service_openapi_definitions_runtime FOREIGN KEY (runtime_id) REFERENCES runtimes (runtime_id) ON DELETE CASCADE
);

CREATE INDEX idx_bi_svc_openapi_def_runtime_id ON bi_service_openapi_definitions (runtime_id);

CREATE OR REPLACE TRIGGER trg_bi_svc_openapi_def_updated
BEFORE UPDATE ON bi_service_openapi_definitions
FOR EACH ROW
BEGIN
    :NEW.updated_at := CURRENT_TIMESTAMP;
END;
/

-- Workflow metadata document published by a runtime's ICP bridge (one row per runtime)
CREATE TABLE bi_workflow_metadata (
  runtime_id   CHAR(36) NOT NULL,
  metadata     CLOB NOT NULL,
  capabilities VARCHAR2(512 CHAR),
  task_queue VARCHAR2(255 CHAR),
  created_at   TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_at   TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  PRIMARY KEY (runtime_id),
  CONSTRAINT fk_bi_workflow_metadata_runtime FOREIGN KEY (runtime_id) REFERENCES runtimes (runtime_id) ON DELETE CASCADE
);

CREATE OR REPLACE TRIGGER trg_bi_workflow_metadata_updated
BEFORE UPDATE ON bi_workflow_metadata
FOR EACH ROW
BEGIN
    :NEW.updated_at := CURRENT_TIMESTAMP;
END;
/


-- ============================================================================
-- TUNNELED OPERATIONS (derived state, shared across ICP nodes)
-- ============================================================================
-- One generic table for the work the control plane tunnels to a runtime over its heartbeat:
-- a read whose answer is cached and re-served while it refreshes, or a mutation whose outcome
-- is queued and polled for. It knows nothing of workflows — `kind` says what a row is about,
-- `cacheable` which of the two it is, and `data` carries the rest, so a second feature
-- needing the same shape adds a kind rather than a table.
--
-- This is DERIVED state. An upgrade may drop and recreate the table, and nothing in it needs
-- migrating — losing a row costs one refetch, or one caller being told their operation was
-- never confirmed.
--
-- What earns a column is what a WHERE clause needs; everything else lives in `data`. The ICP
-- supports five database engines, and portable JSON predicates across them do not exist:
--   op_id       the row's identity: a read's COMPUTED key sha256(kind|owner|request|identity),
--               or a mutation's caller/decision-derived id, so a resubmission collides
--   cacheable   read (re-served while stale) vs mutation (one row, one outcome)
--   owner       the scope a row belongs to; what a read claim filters on
--   target      the runtime a mutation is addressed to (null for a read — any runtime answers)
--   token       a read's in-flight attempt, which fences a late answer from a superseded one
--   expires_at  epoch SECONDS, not a timestamp: every read, claim and sweep compares it, and
--               integers compare identically on all five engines while timestamp arithmetic
--               needs four different implementations (see storage/database_dialect.bal). It is
--               the current phase's deadline — a read's staleness horizon, a mutation's
--               delivery deadline
--
-- No foreign key, deliberately: a K8S deployment DELETEs runtime rows when they go offline,
-- and ON DELETE CASCADE would discard the record of an operation whose outcome nobody has
-- established - the one thing here worth keeping.

CREATE TABLE tunneled_operation (
    op_id VARCHAR2(100 CHAR) NOT NULL,
    kind VARCHAR2(64 CHAR) NOT NULL,
    cacheable NUMBER(1) NOT NULL CHECK (cacheable IN (0, 1)),
    owner VARCHAR2(200 CHAR) NOT NULL,
    target VARCHAR2(36 CHAR),
    token VARCHAR2(36 CHAR),
    status VARCHAR2(16 CHAR) NOT NULL,
    issued_at NUMBER(19) NOT NULL,
    expires_at NUMBER(19) NOT NULL,
    claimed_at NUMBER(19),
    delivered_at NUMBER(19),
    completed_at NUMBER(19),
    data CLOB,
    result CLOB,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    PRIMARY KEY (op_id)
);

CREATE INDEX idx_tunop_read_claim ON tunneled_operation (owner, token, claimed_at);
CREATE INDEX idx_tunop_mutation_claim ON tunneled_operation (target, status, issued_at);
CREATE INDEX idx_tunop_expiry ON tunneled_operation (expires_at);
CREATE INDEX idx_tunop_cleanup ON tunneled_operation (status, completed_at);


-- Listeners bound to a runtime (e.g., HTTP/HTTPS)
CREATE TABLE bi_service_listener_bindings (
  runtime_id       CHAR(36) NOT NULL,
  service_name     VARCHAR2(100 CHAR) NOT NULL,
  service_package  VARCHAR2(200 CHAR) NOT NULL,
  listener_name    VARCHAR2(100 CHAR) NOT NULL,
  created_at       TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  PRIMARY KEY (runtime_id, service_name, service_package, listener_name),
  CONSTRAINT fk_bi_slb_runtime FOREIGN KEY (runtime_id) REFERENCES runtimes (runtime_id) ON DELETE CASCADE
);
CREATE INDEX idx_slb_service ON bi_service_listener_bindings (runtime_id, service_name, service_package);
CREATE INDEX idx_slb_listener ON bi_service_listener_bindings (runtime_id, listener_name);

CREATE TABLE bi_runtime_listener_artifacts (
    runtime_id CHAR(36) NOT NULL,
    listener_name VARCHAR2(100 CHAR) NOT NULL,
    listener_package VARCHAR2(200 CHAR) NOT NULL,
    protocol VARCHAR2(20 CHAR) DEFAULT 'HTTP' NULL,
    listener_host VARCHAR2(100 CHAR),
    listener_port NUMBER(10),
    state VARCHAR2(20 CHAR) DEFAULT 'enabled' NOT NULL CHECK (state IN (
        'enabled',
        'disabled'
    )),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    PRIMARY KEY (runtime_id, listener_name),
    CONSTRAINT fk_bi_runtime_listener_artifacts_runtime FOREIGN KEY (runtime_id) REFERENCES runtimes (runtime_id) ON DELETE CASCADE
);

CREATE INDEX idx_rl_runtime_id ON bi_runtime_listener_artifacts (runtime_id);
CREATE INDEX idx_rl_listener_name ON bi_runtime_listener_artifacts (listener_name);
CREATE INDEX idx_rl_protocol ON bi_runtime_listener_artifacts (protocol);
CREATE INDEX idx_rl_state ON bi_runtime_listener_artifacts (state);

CREATE OR REPLACE TRIGGER trg_bi_runtime_listener_updated
BEFORE UPDATE ON bi_runtime_listener_artifacts
FOR EACH ROW
BEGIN
    :NEW.updated_at := CURRENT_TIMESTAMP;
END;
/

-- Automation artifacts (main function) for BI integrations
CREATE TABLE bi_automation_artifacts (
    runtime_id CHAR(36) NOT NULL,
    package_org VARCHAR2(200 CHAR) NOT NULL,
    package_name VARCHAR2(200 CHAR) NOT NULL,
    package_version VARCHAR2(50 CHAR) NOT NULL,
    execution_timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    PRIMARY KEY (runtime_id, execution_timestamp),
    CONSTRAINT fk_bi_automation_artifacts_runtime FOREIGN KEY (runtime_id) REFERENCES runtimes (runtime_id) ON DELETE CASCADE
);

CREATE INDEX idx_ba_runtime_id ON bi_automation_artifacts (runtime_id);
CREATE INDEX idx_ba_package_name ON bi_automation_artifacts (package_name);
CREATE INDEX idx_ba_execution_timestamp ON bi_automation_artifacts (execution_timestamp);

CREATE OR REPLACE TRIGGER trg_bi_automation_updated_at
BEFORE UPDATE ON bi_automation_artifacts
FOR EACH ROW
BEGIN
    :NEW.updated_at := CURRENT_TIMESTAMP;
END;
/

CREATE TABLE bi_automation_execution_history (
    execution_id CHAR(36) NOT NULL,
    runtime_id CHAR(36) NOT NULL,
    package_org VARCHAR2(200 CHAR) NOT NULL,
    package_name VARCHAR2(200 CHAR) NOT NULL,
    package_version VARCHAR2(50 CHAR) NOT NULL,
    execution_timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    PRIMARY KEY (execution_id),
    CONSTRAINT fk_bi_automation_execution_history_runtime FOREIGN KEY (runtime_id) REFERENCES runtimes (runtime_id) ON DELETE CASCADE
);

CREATE INDEX idx_baeh_runtime_id ON bi_automation_execution_history (runtime_id);
CREATE INDEX idx_baeh_package_name ON bi_automation_execution_history (package_name);
CREATE INDEX idx_baeh_execution_timestamp ON bi_automation_execution_history (execution_timestamp);

-- Runtime log levels for BI components
CREATE TABLE bi_runtime_log_levels (
    runtime_id CHAR(36) NOT NULL,
    component_name VARCHAR2(200 CHAR) NOT NULL,
    log_level VARCHAR2(20 CHAR) NOT NULL CHECK (log_level IN ('DEBUG', 'ERROR', 'INFO', 'WARN')),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    PRIMARY KEY (runtime_id, component_name),
    CONSTRAINT fk_bi_runtime_log_levels_runtime FOREIGN KEY (runtime_id) REFERENCES runtimes (runtime_id) ON DELETE CASCADE
);

CREATE INDEX idx_rll_runtime_id ON bi_runtime_log_levels (runtime_id);
CREATE INDEX idx_rll_component_name ON bi_runtime_log_levels (component_name);
CREATE INDEX idx_rll_log_level ON bi_runtime_log_levels (log_level);

CREATE OR REPLACE TRIGGER trg_bi_runtime_log_levels_updated
BEFORE UPDATE ON bi_runtime_log_levels
FOR EACH ROW
BEGIN
    :NEW.updated_at := CURRENT_TIMESTAMP;
END;
/

-- ============================================================================
-- MI-SPECIFIC ARTIFACT TABLES
-- ============================================================================

-- REST APIs (MI)
CREATE TABLE mi_api_artifacts (
    runtime_id CHAR(36) NOT NULL,
    api_name VARCHAR2(200 CHAR) NOT NULL,
    artifact_id CHAR(36) NOT NULL UNIQUE,
    url VARCHAR2(500 CHAR) NOT NULL,
    urls CLOB NULL, -- JSON array of URLs
    context VARCHAR2(500 CHAR) NOT NULL,
    version VARCHAR2(50 CHAR) NULL,
    state VARCHAR2(20 CHAR) DEFAULT 'enabled' NOT NULL CHECK (state IN (
        'enabled',
        'disabled'
    )),
    tracing VARCHAR2(20 CHAR) DEFAULT 'disabled' NOT NULL,
    statistics VARCHAR2(20 CHAR) DEFAULT 'disabled' NOT NULL,
    composite_app VARCHAR2(200 CHAR) NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    PRIMARY KEY (runtime_id, api_name),
    CONSTRAINT fk_mi_api_artifacts_runtime FOREIGN KEY (runtime_id) REFERENCES runtimes (runtime_id) ON DELETE CASCADE
);

CREATE INDEX idx_ra_runtime_id ON mi_api_artifacts (runtime_id);
CREATE INDEX idx_ra_api_name ON mi_api_artifacts (api_name);
-- idx_artifact_id omitted: covered by the UNIQUE constraint on artifact_id (ORA-01408).
CREATE INDEX idx_ra_state ON mi_api_artifacts (state);

CREATE OR REPLACE TRIGGER trg_mi_api_artifacts_updated_at
BEFORE UPDATE ON mi_api_artifacts
FOR EACH ROW
BEGIN
    :NEW.updated_at := CURRENT_TIMESTAMP;
END;
/

-- API Resources (MI) - Resources inside an API
CREATE TABLE mi_api_resource_artifacts (
    runtime_id CHAR(36) NOT NULL,
    api_name VARCHAR2(200 CHAR) NOT NULL,
    resource_path VARCHAR2(1000 CHAR) NOT NULL,
    methods VARCHAR2(20 CHAR) NOT NULL, -- Single HTTP method as string (e.g., "POST", "GET")
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    PRIMARY KEY (runtime_id, api_name, resource_path),
    CONSTRAINT fk_mi_api_resource_artifacts_runtime FOREIGN KEY (runtime_id) REFERENCES runtimes (runtime_id) ON DELETE CASCADE
);

CREATE INDEX idx_rar_runtime_api ON mi_api_resource_artifacts (runtime_id, api_name);
CREATE INDEX idx_rar_resource_path ON mi_api_resource_artifacts (resource_path);
CREATE INDEX idx_rar_methods ON mi_api_resource_artifacts (methods);

CREATE OR REPLACE TRIGGER trg_mi_api_resource_updated_at
BEFORE UPDATE ON mi_api_resource_artifacts
FOR EACH ROW
BEGIN
    :NEW.updated_at := CURRENT_TIMESTAMP;
END;
/

-- Proxy Services (MI)
CREATE TABLE mi_proxy_service_artifacts (
    runtime_id CHAR(36) NOT NULL,
    proxy_name VARCHAR2(200 CHAR) NOT NULL,
    artifact_id CHAR(36) NOT NULL UNIQUE,
    state VARCHAR2(20 CHAR) DEFAULT 'enabled' NOT NULL CHECK (state IN (
        'enabled',
        'disabled'
    )),
    tracing VARCHAR2(20 CHAR) DEFAULT 'disabled' NOT NULL,
    statistics VARCHAR2(20 CHAR) DEFAULT 'disabled' NOT NULL,
    composite_app VARCHAR2(200 CHAR) NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    PRIMARY KEY (runtime_id, proxy_name),
    CONSTRAINT fk_mi_proxy_service_artifacts_runtime FOREIGN KEY (runtime_id) REFERENCES runtimes (runtime_id) ON DELETE CASCADE
);

CREATE INDEX idx_rps_runtime_id ON mi_proxy_service_artifacts (runtime_id);
CREATE INDEX idx_rps_proxy_name ON mi_proxy_service_artifacts (proxy_name);
-- idx_artifact_id omitted: covered by the UNIQUE constraint on artifact_id (ORA-01408).
CREATE INDEX idx_rps_state ON mi_proxy_service_artifacts (state);

CREATE OR REPLACE TRIGGER trg_mi_proxy_service_updated_at
BEFORE UPDATE ON mi_proxy_service_artifacts
FOR EACH ROW
BEGIN
    :NEW.updated_at := CURRENT_TIMESTAMP;
END;
/

-- Proxy Service Endpoints (MI)
CREATE TABLE mi_proxy_service_endpoint_artifacts (
    runtime_id CHAR(36) NOT NULL,
    proxy_name VARCHAR2(200 CHAR) NOT NULL,
    endpoint_url VARCHAR2(500 CHAR) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    PRIMARY KEY (runtime_id, proxy_name, endpoint_url),
    CONSTRAINT fk_mi_proxy_service_endpoint_artifacts_runtime FOREIGN KEY (runtime_id) REFERENCES runtimes (runtime_id) ON DELETE CASCADE
);

CREATE INDEX idx_rpse_runtime_id ON mi_proxy_service_endpoint_artifacts (runtime_id);
CREATE INDEX idx_rpse_proxy_name ON mi_proxy_service_endpoint_artifacts (proxy_name);

CREATE OR REPLACE TRIGGER trg_mi_proxy_svc_ep_updated_at
BEFORE UPDATE ON mi_proxy_service_endpoint_artifacts
FOR EACH ROW
BEGIN
    :NEW.updated_at := CURRENT_TIMESTAMP;
END;
/

-- Endpoints (MI)
CREATE TABLE mi_endpoint_artifacts (
    runtime_id CHAR(36) NOT NULL,
    endpoint_name VARCHAR2(200 CHAR) NOT NULL,
    artifact_id CHAR(36) NOT NULL UNIQUE,
    endpoint_type VARCHAR2(100 CHAR) NOT NULL,
    state VARCHAR2(20 CHAR) DEFAULT 'enabled' NOT NULL CHECK (state IN (
        'enabled',
        'disabled'
    )),
    tracing VARCHAR2(20 CHAR) DEFAULT 'disabled' NOT NULL,
    statistics VARCHAR2(20 CHAR) DEFAULT 'disabled' NOT NULL,
    composite_app VARCHAR2(200 CHAR) NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    PRIMARY KEY (runtime_id, endpoint_name),
    CONSTRAINT fk_mi_endpoint_artifacts_runtime FOREIGN KEY (runtime_id) REFERENCES runtimes (runtime_id) ON DELETE CASCADE
);

CREATE INDEX idx_re_runtime_id ON mi_endpoint_artifacts (runtime_id);
CREATE INDEX idx_re_endpoint_name ON mi_endpoint_artifacts (endpoint_name);
-- idx_artifact_id omitted: covered by the UNIQUE constraint on artifact_id (ORA-01408).
CREATE INDEX idx_re_endpoint_type ON mi_endpoint_artifacts (endpoint_type);
CREATE INDEX idx_re_state ON mi_endpoint_artifacts (state);

CREATE OR REPLACE TRIGGER trg_mi_endpoint_updated_at
BEFORE UPDATE ON mi_endpoint_artifacts
FOR EACH ROW
BEGIN
    :NEW.updated_at := CURRENT_TIMESTAMP;
END;
/

-- Endpoint Attributes (MI)
CREATE TABLE mi_endpoint_attribute_artifacts (
    runtime_id CHAR(36) NOT NULL,
    endpoint_name VARCHAR2(200 CHAR) NOT NULL,
    attribute_name VARCHAR2(200 CHAR) NOT NULL,
    attribute_value CLOB NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    PRIMARY KEY (runtime_id, endpoint_name, attribute_name),
    CONSTRAINT fk_mi_endpoint_attribute_artifacts_runtime FOREIGN KEY (runtime_id) REFERENCES runtimes (runtime_id) ON DELETE CASCADE
);

CREATE INDEX idx_rea_runtime_id ON mi_endpoint_attribute_artifacts (runtime_id);
CREATE INDEX idx_rea_endpoint_name ON mi_endpoint_attribute_artifacts (endpoint_name);
CREATE INDEX idx_rea_attribute_name ON mi_endpoint_attribute_artifacts (attribute_name);

CREATE OR REPLACE TRIGGER trg_mi_endpoint_attr_updated_at
BEFORE UPDATE ON mi_endpoint_attribute_artifacts
FOR EACH ROW
BEGIN
    :NEW.updated_at := CURRENT_TIMESTAMP;
END;
/

-- Inbound Endpoints (MI)
CREATE TABLE mi_inbound_endpoint_artifacts (
    runtime_id CHAR(36) NOT NULL,
    inbound_name VARCHAR2(200 CHAR) NOT NULL,
    artifact_id CHAR(36) NOT NULL UNIQUE,
    protocol VARCHAR2(50 CHAR) NULL,
    sequence VARCHAR2(200 CHAR) NULL,
    statistics VARCHAR2(20 CHAR) NULL,
    on_error VARCHAR2(200 CHAR) NULL,
    state VARCHAR2(20 CHAR) DEFAULT 'enabled' NOT NULL CHECK (state IN (
        'enabled',
        'disabled'
    )),
    tracing VARCHAR2(20 CHAR) DEFAULT 'disabled' NOT NULL,
    composite_app VARCHAR2(200 CHAR) NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    PRIMARY KEY (runtime_id, inbound_name),
    CONSTRAINT fk_mi_inbound_endpoint_artifacts_runtime FOREIGN KEY (runtime_id) REFERENCES runtimes (runtime_id) ON DELETE CASCADE
);

CREATE INDEX idx_rie_runtime_id ON mi_inbound_endpoint_artifacts (runtime_id);
CREATE INDEX idx_rie_inbound_name ON mi_inbound_endpoint_artifacts (inbound_name);
-- idx_artifact_id omitted: covered by the UNIQUE constraint on artifact_id (ORA-01408).
CREATE INDEX idx_rie_protocol ON mi_inbound_endpoint_artifacts (protocol);
CREATE INDEX idx_rie_state ON mi_inbound_endpoint_artifacts (state);

CREATE OR REPLACE TRIGGER trg_mi_inbound_ep_updated_at
BEFORE UPDATE ON mi_inbound_endpoint_artifacts
FOR EACH ROW
BEGIN
    :NEW.updated_at := CURRENT_TIMESTAMP;
END;
/

-- Sequences (MI)
CREATE TABLE mi_sequence_artifacts (
    runtime_id CHAR(36) NOT NULL,
    sequence_name VARCHAR2(200 CHAR) NOT NULL,
    artifact_id CHAR(36) NOT NULL UNIQUE,
    sequence_type VARCHAR2(100 CHAR) NULL,
    container VARCHAR2(200 CHAR) NULL,
    state VARCHAR2(20 CHAR) DEFAULT 'enabled' NOT NULL CHECK (state IN (
        'enabled',
        'disabled'
    )),
    tracing VARCHAR2(20 CHAR) DEFAULT 'disabled' NOT NULL,
    statistics VARCHAR2(20 CHAR) DEFAULT 'disabled' NOT NULL,
    composite_app VARCHAR2(200 CHAR) NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    PRIMARY KEY (runtime_id, sequence_name),
    CONSTRAINT fk_mi_sequence_artifacts_runtime FOREIGN KEY (runtime_id) REFERENCES runtimes (runtime_id) ON DELETE CASCADE
);

CREATE INDEX idx_rseq_runtime_id ON mi_sequence_artifacts (runtime_id);
CREATE INDEX idx_rseq_sequence_name ON mi_sequence_artifacts (sequence_name);
-- idx_artifact_id omitted: covered by the UNIQUE constraint on artifact_id (ORA-01408).
CREATE INDEX idx_rseq_sequence_type ON mi_sequence_artifacts (sequence_type);
CREATE INDEX idx_rseq_state ON mi_sequence_artifacts (state);

CREATE OR REPLACE TRIGGER trg_mi_sequence_updated_at
BEFORE UPDATE ON mi_sequence_artifacts
FOR EACH ROW
BEGIN
    :NEW.updated_at := CURRENT_TIMESTAMP;
END;
/

-- Tasks (MI)
CREATE TABLE mi_task_artifacts (
    runtime_id CHAR(36) NOT NULL,
    task_name VARCHAR2(200 CHAR) NOT NULL,
    artifact_id CHAR(36) NOT NULL UNIQUE,
    task_class VARCHAR2(500 CHAR) NULL,
    task_group VARCHAR2(200 CHAR) NULL,
    state VARCHAR2(20 CHAR) DEFAULT 'enabled' NOT NULL CHECK (state IN (
        'enabled',
        'disabled'
    )),
    composite_app VARCHAR2(200 CHAR) NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    PRIMARY KEY (runtime_id, task_name),
    CONSTRAINT fk_mi_task_artifacts_runtime FOREIGN KEY (runtime_id) REFERENCES runtimes (runtime_id) ON DELETE CASCADE
);

CREATE INDEX idx_rtask_runtime_id ON mi_task_artifacts (runtime_id);
CREATE INDEX idx_rtask_task_name ON mi_task_artifacts (task_name);
-- idx_artifact_id omitted: covered by the UNIQUE constraint on artifact_id (ORA-01408).
CREATE INDEX idx_rtask_state ON mi_task_artifacts (state);

CREATE OR REPLACE TRIGGER trg_mi_task_updated_at
BEFORE UPDATE ON mi_task_artifacts
FOR EACH ROW
BEGIN
    :NEW.updated_at := CURRENT_TIMESTAMP;
END;
/

-- Templates (MI)
CREATE TABLE mi_template_artifacts (
    runtime_id CHAR(36) NOT NULL,
    template_name VARCHAR2(200 CHAR) NOT NULL,
    template_type VARCHAR2(100 CHAR) NOT NULL,
    tracing VARCHAR2(20 CHAR) DEFAULT 'disabled' NOT NULL,
    statistics VARCHAR2(20 CHAR) DEFAULT 'disabled' NOT NULL,
    composite_app VARCHAR2(200 CHAR) NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    PRIMARY KEY (runtime_id, template_name),
    CONSTRAINT fk_mi_template_artifacts_runtime FOREIGN KEY (runtime_id) REFERENCES runtimes (runtime_id) ON DELETE CASCADE
);

CREATE INDEX idx_rtemp_runtime_id ON mi_template_artifacts (runtime_id);
CREATE INDEX idx_rtemp_template_name ON mi_template_artifacts (template_name);
CREATE INDEX idx_rtemp_template_type ON mi_template_artifacts (template_type);

CREATE OR REPLACE TRIGGER trg_mi_template_updated_at
BEFORE UPDATE ON mi_template_artifacts
FOR EACH ROW
BEGIN
    :NEW.updated_at := CURRENT_TIMESTAMP;
END;
/

-- Message Stores (MI)
CREATE TABLE mi_message_store_artifacts (
    runtime_id CHAR(36) NOT NULL,
    store_name VARCHAR2(200 CHAR) NOT NULL,
    store_type VARCHAR2(100 CHAR) NOT NULL,
    -- RESERVED WORD: `size` is an Oracle reserved word, so it cannot be an
    -- unquoted identifier. Created as quoted uppercase "SIZE" by agreement
    -- with the application layer, whose queries must reference "SIZE"
    -- (quoted) in their Oracle branches. Do not rename this column.
    "SIZE" NUMBER(19) DEFAULT 0 NOT NULL,
    composite_app VARCHAR2(200 CHAR) NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    PRIMARY KEY (runtime_id, store_name),
    CONSTRAINT fk_mi_message_store_artifacts_runtime FOREIGN KEY (runtime_id) REFERENCES runtimes (runtime_id) ON DELETE CASCADE
);

CREATE INDEX idx_rms_runtime_id ON mi_message_store_artifacts (runtime_id);
CREATE INDEX idx_rms_store_name ON mi_message_store_artifacts (store_name);
CREATE INDEX idx_rms_store_type ON mi_message_store_artifacts (store_type);

CREATE OR REPLACE TRIGGER trg_mi_message_store_updated_at
BEFORE UPDATE ON mi_message_store_artifacts
FOR EACH ROW
BEGIN
    :NEW.updated_at := CURRENT_TIMESTAMP;
END;
/

-- Message Processors (MI)
CREATE TABLE mi_message_processor_artifacts (
    runtime_id CHAR(36) NOT NULL,
    processor_name VARCHAR2(200 CHAR) NOT NULL,
    artifact_id CHAR(36) NOT NULL UNIQUE,
    processor_type VARCHAR2(100 CHAR) NOT NULL,
    processor_class VARCHAR2(500 CHAR) NULL,
    state VARCHAR2(20 CHAR) DEFAULT 'enabled' NOT NULL CHECK (state IN (
        'enabled',
        'disabled'
    )),
    composite_app VARCHAR2(200 CHAR) NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    PRIMARY KEY (runtime_id, processor_name),
    CONSTRAINT fk_mi_message_processor_artifacts_runtime FOREIGN KEY (runtime_id) REFERENCES runtimes (runtime_id) ON DELETE CASCADE
);

CREATE INDEX idx_rmp_runtime_id ON mi_message_processor_artifacts (runtime_id);
CREATE INDEX idx_rmp_processor_name ON mi_message_processor_artifacts (processor_name);
-- idx_artifact_id omitted: covered by the UNIQUE constraint on artifact_id (ORA-01408).
CREATE INDEX idx_rmp_processor_type ON mi_message_processor_artifacts (processor_type);
CREATE INDEX idx_rmp_state ON mi_message_processor_artifacts (state);

CREATE OR REPLACE TRIGGER trg_mi_msg_processor_updated_at
BEFORE UPDATE ON mi_message_processor_artifacts
FOR EACH ROW
BEGIN
    :NEW.updated_at := CURRENT_TIMESTAMP;
END;
/

-- Local Entries (MI)
CREATE TABLE mi_local_entry_artifacts (
    runtime_id CHAR(36) NOT NULL,
    entry_name VARCHAR2(200 CHAR) NOT NULL,
    artifact_id CHAR(36) NOT NULL UNIQUE,
    entry_type VARCHAR2(100 CHAR) NOT NULL,
    entry_value CLOB NULL,
    state VARCHAR2(20 CHAR) DEFAULT 'enabled' NOT NULL CHECK (state IN (
        'enabled',
        'disabled'
    )),
    composite_app VARCHAR2(200 CHAR) NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    PRIMARY KEY (runtime_id, entry_name),
    CONSTRAINT fk_mi_local_entry_artifacts_runtime FOREIGN KEY (runtime_id) REFERENCES runtimes (runtime_id) ON DELETE CASCADE
);

CREATE INDEX idx_rle_runtime_id ON mi_local_entry_artifacts (runtime_id);
CREATE INDEX idx_rle_entry_name ON mi_local_entry_artifacts (entry_name);
-- idx_artifact_id omitted: covered by the UNIQUE constraint on artifact_id (ORA-01408).
CREATE INDEX idx_rle_entry_type ON mi_local_entry_artifacts (entry_type);
CREATE INDEX idx_rle_state ON mi_local_entry_artifacts (state);

CREATE OR REPLACE TRIGGER trg_mi_local_entry_updated_at
BEFORE UPDATE ON mi_local_entry_artifacts
FOR EACH ROW
BEGIN
    :NEW.updated_at := CURRENT_TIMESTAMP;
END;
/

-- Data Services (MI)
CREATE TABLE mi_data_service_artifacts (
    runtime_id CHAR(36) NOT NULL,
    service_name VARCHAR2(200 CHAR) NOT NULL,
    artifact_id CHAR(36) NOT NULL UNIQUE,
    description CLOB NULL,
    wsdl CLOB NULL,
    state VARCHAR2(20 CHAR) DEFAULT 'Active' NOT NULL CHECK (state IN ('Active', 'Faulty')),
    composite_app VARCHAR2(200 CHAR) NULL,
    error_message CLOB NULL, -- Error message when state is Faulty (data service failed to deploy)
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    PRIMARY KEY (runtime_id, service_name),
    CONSTRAINT fk_mi_data_service_artifacts_runtime FOREIGN KEY (runtime_id) REFERENCES runtimes (runtime_id) ON DELETE CASCADE
);

CREATE INDEX idx_rds_runtime_id ON mi_data_service_artifacts (runtime_id);
CREATE INDEX idx_rds_service_name ON mi_data_service_artifacts (service_name);
-- idx_artifact_id omitted: covered by the UNIQUE constraint on artifact_id (ORA-01408).
CREATE INDEX idx_rds_state ON mi_data_service_artifacts (state);

CREATE OR REPLACE TRIGGER trg_mi_data_service_updated_at
BEFORE UPDATE ON mi_data_service_artifacts
FOR EACH ROW
BEGIN
    :NEW.updated_at := CURRENT_TIMESTAMP;
END;
/

-- Composite Apps (MI)
CREATE TABLE mi_composite_app_artifacts (
    runtime_id CHAR(36) NOT NULL,
    app_name VARCHAR2(200 CHAR) NOT NULL,
    version VARCHAR2(50 CHAR) NULL,
    state VARCHAR2(20 CHAR) DEFAULT 'Active' NOT NULL CHECK (state IN ('Active', 'Faulty')),
    error_message CLOB NULL, -- Error message when state is Faulty
    artifacts VARCHAR2(4000 CHAR) NULL, -- JSON array serialized as string (convert to JSON in app code when needed)
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    PRIMARY KEY (runtime_id, app_name),
    CONSTRAINT fk_mi_composite_app_artifacts_runtime FOREIGN KEY (runtime_id) REFERENCES runtimes (runtime_id) ON DELETE CASCADE
);

CREATE INDEX idx_rca_runtime_id ON mi_composite_app_artifacts (runtime_id);
CREATE INDEX idx_rca_app_name ON mi_composite_app_artifacts (app_name);
CREATE INDEX idx_rca_state ON mi_composite_app_artifacts (state);

CREATE OR REPLACE TRIGGER trg_mi_composite_app_updated_at
BEFORE UPDATE ON mi_composite_app_artifacts
FOR EACH ROW
BEGIN
    :NEW.updated_at := CURRENT_TIMESTAMP;
END;
/

-- Data Sources (MI)
CREATE TABLE mi_data_source_artifacts (
    runtime_id CHAR(36) NOT NULL,
    datasource_name VARCHAR2(200 CHAR) NOT NULL,
    datasource_type VARCHAR2(100 CHAR) NULL,
    driver VARCHAR2(500 CHAR) NULL,
    url VARCHAR2(1000 CHAR) NULL,
    username VARCHAR2(255 CHAR) NULL,
    state VARCHAR2(20 CHAR) DEFAULT 'enabled' NOT NULL CHECK (state IN (
        'enabled',
        'disabled'
    )),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    PRIMARY KEY (runtime_id, datasource_name),
    CONSTRAINT fk_mi_data_source_artifacts_runtime FOREIGN KEY (runtime_id) REFERENCES runtimes (runtime_id) ON DELETE CASCADE
);

CREATE INDEX idx_rdatasrc_runtime_id ON mi_data_source_artifacts (runtime_id);
CREATE INDEX idx_rdatasrc_datasource_name ON mi_data_source_artifacts (datasource_name);
CREATE INDEX idx_rdatasrc_datasource_type ON mi_data_source_artifacts (datasource_type);
CREATE INDEX idx_rdatasrc_state ON mi_data_source_artifacts (state);

CREATE OR REPLACE TRIGGER trg_mi_data_source_updated_at
BEFORE UPDATE ON mi_data_source_artifacts
FOR EACH ROW
BEGIN
    :NEW.updated_at := CURRENT_TIMESTAMP;
END;
/

-- Connectors (MI)
CREATE TABLE mi_connector_artifacts (
    runtime_id CHAR(36) NOT NULL,
    connector_name VARCHAR2(200 CHAR) NOT NULL,
    artifact_id CHAR(36) NOT NULL UNIQUE,
    package VARCHAR2(200 CHAR) NOT NULL,
    version VARCHAR2(50 CHAR) NULL,
    description VARCHAR2(500 CHAR) NULL,
    state VARCHAR2(20 CHAR) DEFAULT 'enabled' NOT NULL CHECK (state IN (
        'enabled',
        'disabled'
    )),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    PRIMARY KEY (runtime_id, connector_name, package),
    CONSTRAINT fk_mi_connector_artifacts_runtime FOREIGN KEY (runtime_id) REFERENCES runtimes (runtime_id) ON DELETE CASCADE
);

CREATE INDEX idx_rconn_runtime_id ON mi_connector_artifacts (runtime_id);
CREATE INDEX idx_rconn_connector_name ON mi_connector_artifacts (connector_name);
-- idx_artifact_id omitted: covered by the UNIQUE constraint on artifact_id (ORA-01408).
CREATE INDEX idx_rconn_state ON mi_connector_artifacts (state);

CREATE OR REPLACE TRIGGER trg_mi_connector_updated_at
BEFORE UPDATE ON mi_connector_artifacts
FOR EACH ROW
BEGIN
    :NEW.updated_at := CURRENT_TIMESTAMP;
END;
/

-- Registry Resources (MI)
CREATE TABLE mi_registry_resource_artifacts (
    runtime_id CHAR(36) NOT NULL,
    resource_name VARCHAR2(200 CHAR) NOT NULL,
    resource_type VARCHAR2(100 CHAR) NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    PRIMARY KEY (runtime_id, resource_name),
    CONSTRAINT fk_mi_registry_resource_artifacts_runtime FOREIGN KEY (runtime_id) REFERENCES runtimes (runtime_id) ON DELETE CASCADE
);

CREATE INDEX idx_rrr_runtime_id ON mi_registry_resource_artifacts (runtime_id);
CREATE INDEX idx_rrr_resource_name ON mi_registry_resource_artifacts (resource_name);

CREATE OR REPLACE TRIGGER trg_mi_registry_res_updated_at
BEFORE UPDATE ON mi_registry_resource_artifacts
FOR EACH ROW
BEGIN
    :NEW.updated_at := CURRENT_TIMESTAMP;
END;
/

-- ============================================================================
-- CONTROL COMMANDS
-- ============================================================================

CREATE TABLE mi_runtime_control_commands (
    runtime_id CHAR(36) NOT NULL,
    component_id CHAR(36) NOT NULL,
    artifact_name VARCHAR2(200 CHAR) NOT NULL,
    artifact_type VARCHAR2(100 CHAR) NOT NULL,
    action VARCHAR2(50 CHAR) NOT NULL, -- enable_artifact, disable_artifact, enable_tracing, disable_tracing
    status VARCHAR2(20 CHAR) DEFAULT 'pending' NOT NULL CHECK (status IN (
        'pending',
        'sent',
        'acknowledged',
        'completed',
        'failed',
        'timeout'
    )),
    issued_at TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP(6) NOT NULL,
    sent_at TIMESTAMP(6) NULL,
    acknowledged_at TIMESTAMP(6) NULL,
    completed_at TIMESTAMP(6) NULL,
    error_message CLOB NULL,
    issued_by CHAR(36) NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    PRIMARY KEY (runtime_id, component_id, artifact_name, artifact_type),
    CONSTRAINT fk_mi_runtime_control_cmd_runtime FOREIGN KEY (runtime_id) REFERENCES runtimes (runtime_id) ON DELETE CASCADE,
    CONSTRAINT fk_mi_runtime_control_cmd_component FOREIGN KEY (component_id) REFERENCES components (component_id) ON DELETE CASCADE,
    CONSTRAINT fk_mi_runtime_control_cmd_issued_by FOREIGN KEY (issued_by) REFERENCES users (user_id) ON DELETE SET NULL
);

CREATE INDEX idx_mi_runtime_id ON mi_runtime_control_commands (runtime_id);
CREATE INDEX idx_mi_component_id ON mi_runtime_control_commands (component_id);
CREATE INDEX idx_mi_artifact_name ON mi_runtime_control_commands (artifact_name);
CREATE INDEX idx_mi_artifact_type ON mi_runtime_control_commands (artifact_type);
CREATE INDEX idx_mi_status ON mi_runtime_control_commands (status);
CREATE INDEX idx_mi_issued_at ON mi_runtime_control_commands (issued_at);
CREATE INDEX idx_mi_action ON mi_runtime_control_commands (action);
CREATE INDEX idx_mi_issued_by ON mi_runtime_control_commands (issued_by);

CREATE OR REPLACE TRIGGER trg_mi_runtime_ctl_cmd_updated
BEFORE UPDATE ON mi_runtime_control_commands
FOR EACH ROW
BEGIN
    :NEW.updated_at := CURRENT_TIMESTAMP;
END;
/

-- ============================================================================
-- Reconciliation Engine Tables
-- ============================================================================

CREATE TABLE reconcile_desired_state (
    component_id CHAR(36) NOT NULL,
    env_id CHAR(36) NOT NULL,
    artifact_name VARCHAR2(200 CHAR) NOT NULL,
    artifact_type VARCHAR2(100 CHAR) NOT NULL,
    state_key VARCHAR2(255 CHAR) NOT NULL,
    state_value VARCHAR2(1024 CHAR),
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    PRIMARY KEY (component_id, env_id, artifact_name, artifact_type, state_key)
);

CREATE INDEX idx_reconcile_desired_comp_env ON reconcile_desired_state (component_id, env_id);

CREATE OR REPLACE TRIGGER trg_reconcile_desired_updated
BEFORE UPDATE ON reconcile_desired_state
FOR EACH ROW
BEGIN
    :NEW.updated_at := CURRENT_TIMESTAMP;
END;
/

CREATE TABLE reconcile_observed_state (
    runtime_id CHAR(36) NOT NULL,
    component_id CHAR(36) NOT NULL,
    env_id CHAR(36) NOT NULL,
    artifact_name VARCHAR2(200 CHAR) NOT NULL,
    artifact_type VARCHAR2(100 CHAR) NOT NULL,
    state_key VARCHAR2(255 CHAR) NOT NULL,
    state_value VARCHAR2(1024 CHAR),
    optimistic NUMBER(1) DEFAULT 0 NOT NULL CHECK (optimistic IN (0, 1)),
    heartbeat_gen NUMBER(19) DEFAULT 0 NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    PRIMARY KEY (runtime_id, artifact_name, artifact_type, state_key)
);

CREATE INDEX idx_reconcile_observed_comp_env ON reconcile_observed_state (component_id, env_id);

CREATE OR REPLACE TRIGGER trg_reconcile_observed_updated
BEFORE UPDATE ON reconcile_observed_state
FOR EACH ROW
BEGIN
    :NEW.updated_at := CURRENT_TIMESTAMP;
END;
/

CREATE TABLE reconcile_backoff (
    runtime_id CHAR(36) NOT NULL,
    artifact_name VARCHAR2(200 CHAR) NOT NULL,
    artifact_type VARCHAR2(100 CHAR) NOT NULL,
    state_key VARCHAR2(255 CHAR) NOT NULL,
    attempt_count NUMBER(10) DEFAULT 0 NOT NULL,
    has_error NUMBER(10) DEFAULT 0 NOT NULL,
    next_attempt NUMBER(19) DEFAULT 0 NOT NULL,
    PRIMARY KEY (runtime_id, artifact_name, artifact_type, state_key)
);

CREATE TABLE mi_logger_intended_state (
    component_id CHAR(36) NOT NULL,
    logger_name VARCHAR2(500 CHAR) NOT NULL,
    log_level VARCHAR2(20 CHAR) NOT NULL CHECK (log_level IN ('OFF', 'TRACE', 'DEBUG', 'INFO', 'WARN', 'ERROR', 'FATAL')),
    issued_at TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP(6) NOT NULL,
    issued_by CHAR(36),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    PRIMARY KEY (component_id, logger_name),
    CONSTRAINT fk_mi_logger_state_component FOREIGN KEY (component_id) REFERENCES components (component_id) ON DELETE CASCADE,
    CONSTRAINT fk_mi_logger_state_issued_by FOREIGN KEY (issued_by) REFERENCES users (user_id) ON DELETE SET NULL
);

CREATE INDEX idx_mi_logger_intended_state_component_id ON mi_logger_intended_state (component_id);
CREATE INDEX idx_mi_logger_intended_state_logger_name ON mi_logger_intended_state (logger_name);
CREATE INDEX idx_mi_logger_intended_state_log_level ON mi_logger_intended_state (log_level);

CREATE OR REPLACE TRIGGER trg_mi_logger_state_updated_at
BEFORE UPDATE ON mi_logger_intended_state
FOR EACH ROW
BEGIN
    :NEW.updated_at := CURRENT_TIMESTAMP;
END;
/

-- ============================================================================
-- AUDIT & EVENTS
-- ============================================================================

CREATE TABLE audit_logs (
    id NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    runtime_id CHAR(36) NULL,
    user_id CHAR(36) NULL,
    action VARCHAR2(100 CHAR) NOT NULL,
    resource_type VARCHAR2(50 CHAR) NULL, -- runtime, service, listener, command
    resource_id VARCHAR2(200 CHAR) NULL,
    details CLOB NULL,
    client_ip VARCHAR2(45 CHAR) NULL, -- IPv6 compatible
    user_agent VARCHAR2(500 CHAR) NULL,
    timestamp TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP(6) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_audit_runtime FOREIGN KEY (runtime_id) REFERENCES runtimes (runtime_id) ON DELETE CASCADE,
    CONSTRAINT fk_audit_user FOREIGN KEY (user_id) REFERENCES users (user_id) ON DELETE SET NULL
);

CREATE INDEX idx_al_runtime_id ON audit_logs (runtime_id);
CREATE INDEX idx_al_user_id ON audit_logs (user_id);
CREATE INDEX idx_al_action ON audit_logs (action);
CREATE INDEX idx_al_resource_type ON audit_logs (resource_type);
CREATE INDEX idx_al_timestamp ON audit_logs (timestamp);
CREATE INDEX idx_al_client_ip ON audit_logs (client_ip);

CREATE TABLE system_events (
    id NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    event_type VARCHAR2(50 CHAR) NOT NULL, -- heartbeat_timeout, runtime_offline, system_error
    severity VARCHAR2(20 CHAR) DEFAULT 'INFO' NOT NULL CHECK (severity IN (
        'INFO',
        'WARN',
        'ERROR',
        'CRITICAL'
    )),
    source VARCHAR2(100 CHAR) NULL, -- runtime_id or system component
    message CLOB NOT NULL,
    metadata CLOB NULL,
    resolved NUMBER(1) DEFAULT 0 NOT NULL CHECK (resolved IN (0, 1)),
    resolved_at TIMESTAMP NULL,
    resolved_by CHAR(36) NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_sys_events_resolved_by FOREIGN KEY (resolved_by) REFERENCES users (user_id) ON DELETE SET NULL
);

CREATE INDEX idx_se_event_type ON system_events (event_type);
CREATE INDEX idx_se_severity ON system_events (severity);
CREATE INDEX idx_se_source ON system_events (source);
CREATE INDEX idx_se_resolved ON system_events (resolved);
CREATE INDEX idx_se_created_at ON system_events (created_at);

-- ============================================================================
-- MONITORING & HEALTH
-- ============================================================================

CREATE TABLE runtime_metrics (
    id NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    runtime_id CHAR(36) NOT NULL,
    metric_name VARCHAR2(100 CHAR) NOT NULL,
    metric_value NUMBER(15, 4) NOT NULL,
    metric_unit VARCHAR2(20 CHAR) NULL,
    tags CLOB NULL,
    timestamp TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP(6) NOT NULL,
    CONSTRAINT fk_metrics_runtime FOREIGN KEY (runtime_id) REFERENCES runtimes (runtime_id) ON DELETE CASCADE
);

CREATE INDEX idx_rm_runtime_metric ON runtime_metrics (runtime_id, metric_name);
CREATE INDEX idx_rm_timestamp ON runtime_metrics (timestamp);
CREATE INDEX idx_rm_metric_name ON runtime_metrics (metric_name);

CREATE TABLE health_checks (
    id NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    runtime_id CHAR(36) NOT NULL,
    check_type VARCHAR2(50 CHAR) NOT NULL, -- heartbeat, connectivity, resource
    status VARCHAR2(20 CHAR) NOT NULL CHECK (status IN (
        'HEALTHY',
        'DEGRADED',
        'UNHEALTHY'
    )),
    response_time_ms NUMBER(10) NULL,
    error_message CLOB NULL,
    details CLOB NULL,
    timestamp TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP(6) NOT NULL,
    CONSTRAINT fk_health_runtime FOREIGN KEY (runtime_id) REFERENCES runtimes (runtime_id) ON DELETE CASCADE
);

CREATE INDEX idx_hc_runtime_check ON health_checks (runtime_id, check_type);
CREATE INDEX idx_hc_status ON health_checks (status);
CREATE INDEX idx_hc_timestamp ON health_checks (timestamp);

-- ============================================================================
-- SYSTEM CONFIG
-- ============================================================================

CREATE TABLE system_config (
    config_key VARCHAR2(100 CHAR) NOT NULL PRIMARY KEY,
    config_value CLOB NOT NULL,
    config_type VARCHAR2(20 CHAR) DEFAULT 'STRING' NOT NULL CHECK (config_type IN (
        'STRING',
        'INTEGER',
        'BOOLEAN',
        'JSON'
    )),
    description CLOB NULL,
    is_encrypted NUMBER(1) DEFAULT 0 NOT NULL CHECK (is_encrypted IN (0, 1)),
    updated_by CHAR(36) NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_syscfg_updated_by FOREIGN KEY (updated_by) REFERENCES users (user_id) ON DELETE SET NULL
);

CREATE INDEX idx_sc_config_type ON system_config (config_type);
CREATE INDEX idx_sc_updated_at ON system_config (updated_at);

CREATE OR REPLACE TRIGGER trg_system_config_updated_at
BEFORE UPDATE ON system_config
FOR EACH ROW
BEGIN
    :NEW.updated_at := CURRENT_TIMESTAMP;
END;
/

-- ============================================================================
-- SAMPLE DATA FOR TESTING
-- ============================================================================

-- Note: Default organization and super admin user are created in RBAC V2 SEED DATA section above

-- Note: User credentials are stored in a separate database (credentialsdb)
-- accessed only by the default auth backend. See resources/db/init-scripts/credentials_oracle_init.sql

-- Insert sample environments
INSERT INTO
    environments (
        environment_id,
        name,
        handler,
        description,
        region,
        cluster_id,
        choreo_env,
        external_apim_env_name,
        internal_apim_env_name,
        sandbox_apim_env_name,
        critical,
        dns_prefix,
        created_by
    )
VALUES (
        '750e8400-e29b-41d4-a716-446655440001',
        'dev',
        'dev',
        'Development environment',
        'us-east-1',
        'cluster-abc123',
        'dev',
        'dev-external',
        'dev-internal',
        'dev-sandbox',
        0,
        'dev',
        NULL
    );

INSERT INTO
    environments (
        environment_id,
        name,
        handler,
        description,
        region,
        cluster_id,
        choreo_env,
        external_apim_env_name,
        internal_apim_env_name,
        sandbox_apim_env_name,
        critical,
        dns_prefix,
        created_by
    )
VALUES (
        '750e8400-e29b-41d4-a716-446655440002',
        'prod',
        'prod',
        'Production environment',
        'us-east-1',
        'cluster-abc123',
        'prod',
        'prod-external',
        'prod-internal',
        'prod-sandbox',
        1,
        'prod',
        NULL
    );

COMMIT;
